//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaWeb.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public int EmployeGameId { get; set; }
        public int OptionId { get; set; }
        public decimal Value { get; set; }
        public bool State { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual EmployeeGame EmployeGame { get; set; }
    }
}
