//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaWeb.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelTriviaDBContainer : DbContext
    {
        public ModelTriviaDBContainer()
            : base("name=ModelTriviaDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> CompanySet { get; set; }
        public virtual DbSet<Employee> EmployeeSet { get; set; }
        public virtual DbSet<Game> GameSet { get; set; }
        public virtual DbSet<EmployeeGame> EmployeeGameSet { get; set; }
        public virtual DbSet<Answer> AnswerSet { get; set; }
        public virtual DbSet<Option> OptionSet { get; set; }
        public virtual DbSet<Question> QuestionSet { get; set; }
        public virtual DbSet<Category> CategorySet { get; set; }
    }
}
